[tool.poetry]
name = "vipsy"
version = "0.1.0"
description = ""
authors = ["martinnormark"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyvips = {extras = ["binary"], version = "^2.2.3"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"